version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta para conexões AMQP
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15.0-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pier-Cloud
      - PGPORT=5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "3030:5432"
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pier-Cloud -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  job:
    build: ./job
    ports:
      - 3001:3001
    working_dir: /app-job
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3001 || exit 1"] # Verifica a porta 3001
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - app-network

  worker:
    container_name: app_worker
    build: ./worker
    ports:
      - 3000:3000
    working_dir: /app-worker
    volumes:
      - ./worker/src:/app-worker/src
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      job:
        condition: service_healthy
    environment:
      - APP_PORT=3000
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db # Aqui usamos o nome do serviço no Docker Compose
      - DB_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    command: >
      sh -c "pnpm prisma migrate deploy &&
          pnpm run start"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
      - postgres-network

networks:
  app-network:
  postgres-network:
